### æ’ä»¶è®¾ç½®
# ç³»ç»ŸçŠ¶æ€æ˜¯å¦æ‰€æœ‰äººå¯ç”¨
SystemStatusAll: false
# RedisçŠ¶æ€æ˜¯å¦æ‰€æœ‰äººå¯ç”¨
RedisStatusAll: false
# è‡ªåŠ¨ç‚¹èµ ä¸»äººé»˜è®¤åœ¨ç‚¹èµåå•
AutoLike: true
# è‡ªåŠ¨ç‚¹èµåˆ—è¡¨
AutoLikeList: []
# è°è‰¾ç‰¹æˆ‘ä¿ç•™æ—¶é•¿(å°æ—¶)
whoAtmeTime: 24
# è‰¾ç‰¹å…¨ä½“æ–‡æœ¬
atalltext: "ä¸ğŸˆ·ï¸"
# è‰¾ç‰¹å…¨ä½“åˆ†ç‰‡
atChunkSize: 40

### å·¥å…·è®¾ç½®
# æ˜¯å¦æ‰€æœ‰äººå¯ç”¨Whois
WhoisAll: true
# æ˜¯å¦æ‰€æœ‰äººå¯ç”¨SEO
SeoAll: true
# æ˜¯å¦æ‰€æœ‰äººå¯ç”¨å¤‡æ¡ˆæŸ¥è¯¢
icpBeianAll: true
# æ˜¯å¦æ‰€æœ‰äººå¯ç”¨åŸŸåæŸ¥è¯¢ä»·æ ¼
DomainMinPricingAll: true
# æ˜¯å¦æ‰€æœ‰äººå¯ç”¨ç½‘é¡µæˆªå›¾
webpage: false
# æ˜¯å¦æ‰€æœ‰äººå¯ç”¨Ping
PingAll: true
# Pingæ˜¯å¦ä½¿ç”¨ä»£ç†
PingProxy: false
# Pingä»£ç†è®¾ç½®
PingProxyAddress: ""
# Pingæ¥å£1ä¸º`ç‚¸äº†å—`ç½‘ç«™æˆªå›¾æµ‹é€Ÿ,2ä¸º`ITdog`æµ‹é€Ÿ
PingApi: 2
# Ipinfoæ˜¯å¦æ‰€æœ‰äººå¯ç”¨
IpinfoAll: true
# PingåŠŸèƒ½Ipinfo.ioçš„token
IpinfoToken: ""
# æ˜¯å¦æ‰€æœ‰äººå¯ç”¨Unicodeç¼–ç è§£ç 
UnicodeAll: true
# æ˜¯å¦æ‰€æœ‰äººå¯ç”¨urlç¼–ç è§£ç 
UrlAll: true
# æ˜¯å¦æ‰€æœ‰äººå¯ç”¨è¿›åˆ¶è½¬æ¢
BaseConversionAll: true

### ç½‘ç»œæœç´¢è®¾ç½®
# æ˜¯å¦å¼€å¯æœå½±è§†
SearchMovie: true
# æ˜¯å¦å¼€å¯æœèµ„æº
SearchResource: true
# ç”³è¯·æ¸¸æˆæ˜¯å¦å¼€å¯
apply_game: true
# æ˜¯å¦å¼€å¯ç£åŠ›æœç´¢
SearchMagnet: false

### å®šæ—¶ç¾¤å‘è®¾ç½®
# å®šæ—¶ç¾¤å‘å¼€å…³
GroupScheduler: false
# ç¾¤å‘ç™½åå•bot
GroupSchedulerWhiteBotList: []
# ç¾¤å‘é»‘åå•bot
GroupSchedulerBlackBotList: []
# å®šæ—¶ç¾¤å‘CRONè¡¨è¾¾å¼
GroupSchedulerCron: "0 0 1 * *?" #é»˜è®¤æ¯å¤©1ç‚¹
# å®šæ—¶ç¾¤å‘å†…å®¹
GroupSchedulerMsg: "#å…¨éƒ¨èµæˆ‘"
# å®šæ—¶ç¾¤å‘ç¾¤ç»„
GroupSchedulerGroup: []